spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html

    cache: false     # 开发时关闭缓存，不然无法看到实时页面
    prefix: classpath:/templates/    # 模板对应的路径前缀
    suffix: .html    # 模板对应的文件后缀